TestTaskGAE/urls.py
from django.contrib.auth.views import login, logout
from django.conf.urls.defaults import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from TestTaskGAE.Test.views import chapters, task, end, add_answer, students, test_detail, tests, tests_to_pdf, test_chart, theory_reader, bio, feedback

#admin.autodiscover()
urlpatterns = patterns('',
    (r'^accounts/login/$', login),
    (r'^accounts/logout/$', logout),
    (r'^accounts/profile/$', chapters),
    (r'^chapter/$', chapters),
    (r'^chapter/([\d]*)/$', chapters),
    (r'^chapter/([\d]*)/final/$', chapters, {'final' : True}),
    (r'^chapter/([\d]*)/train/$', chapters, {'final' : False}),
    (r'^chapter/([\d]*)/task/0/$', end),
    (r'^chapter/[\d]*/task/([\d]*)/$', task),
    (r'^chapter/[\d]*/task/([\d]*)/answer/$', add_answer),
    (r'^theory/[\w]*.html$', theory_reader),
    (r'^statistics/students/$', students),
    (r'^statistics/tests/$', tests),
    (r'^statistics/tests/pdf/$', tests_to_pdf, {'chapterId' : 1}),
    (r'^statistics/test/([\d]*)/$', test_detail),
    (r'^statistics/chart/chapter/([\d]*)/student/([\d]*)/$', test_chart),
    (r'^bio/$', bio),
    (r'^feedback/$', feedback),
    # Example:
    # (r'^TestTask/', include('TestTask.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
#    (r'^admin/', include(admin.site.urls)),
    (r'^$', chapters),
)
#urlpatterns += patterns('',
#    url(r'^captcha/', include('captcha.urls')),
#)

TestTaskGAE/Test/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Student (models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    className = models.CharField(max_length=10)
    def __unicode__(self):
        return self.lastName + " " + self.firstName
    class Meta:
        ordering = ['className', 'lastName', 'firstName']

class Chapter (models.Model):
    shortName = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    active = models.BooleanField(default=False)
    timeLimit = models.IntegerField(default=0)
    easy = models.IntegerField(blank=True)
    medium = models.IntegerField(blank=True)
    hard = models.IntegerField(blank=True)
    def __unicode__(self):
        return self.shortName

class Task (models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=400)
    position = models.IntegerField()
    chapter = models.ForeignKey(Chapter)
    complexity = models.IntegerField()
    theoryLink = models.CharField(blank=True, max_length=400)
    def __unicode__(self):
        return  self.title
    class Meta:
        ordering = ['position']

class Option (models.Model):
    text = models.CharField(max_length=80)
    value = models.CharField(max_length=30, blank=True)
    position = models.IntegerField()
    correct = models.BooleanField()
    task = models.ForeignKey(Task)
    def __unicode__(self):
        return self.text
    class Meta:
        ordering = ['position']

class TestSession (models.Model):
    testDate = models.DateField()
    duration = models.IntegerField(blank=True)
    student = models.ForeignKey(User)
    correct = models.IntegerField(blank=True)
    total = models.IntegerField(blank=True)
    final = models.BooleanField()

class TestSequence (models.Model):
    task = models.ForeignKey(Task)
    position = models.IntegerField()
    test_session = models.ForeignKey(TestSession)

class Answer (models.Model):
    testSession = models.ForeignKey(TestSession)
    selected = models.ManyToManyField(Option)
    value = models.CharField(max_length=30, blank=True)
    position = models.IntegerField()
    class Meta:
        ordering = ['position']

class Feedback (models.Model):
    email = models.EmailField(blank=False)
    message = models.CharField(blank=False, max_length=500)
    post_date = models.DateTimeField(blank=False)
    def __unicode__(self):
        return self.post_date.strftime('%d %b %Y') + ' ' + self.email + ' ' + self.message
    class Meta:
        ordering = ['post_date']

TestTaskGAE/Test/forms.py
# coding=UTF-8
from django import forms
#from captcha.fields import CaptchaField

__author__ = 'Frostbite'
class SearchTest(forms.Form):
    name = forms.CharField(max_length = 100, required=False, label="",
                           widget=forms.widgets.TextInput(attrs={'placeholder': u'Учащийся'}))
    em = {"required": u"Введите дату", "invalid": u"Неправильный формат даты"}
    start = forms.DateField(widget=forms.widgets.DateInput(format="%d.%m.%Y", attrs={'placeholder': u'От (дд.мм.гггг)'}),
                            required=False, label="", input_formats = ["%d.%m.%Y"], error_messages = em)

    end = forms.DateField(widget=forms.widgets.DateInput(format="%d.%m.%Y", attrs={'placeholder': u'До (дд.мм.гггг)'}),
                          required=False, label="", input_formats= ["%d.%m.%Y"], error_messages= em)
    page = forms.IntegerField(required=False, widget=forms.widgets.HiddenInput())

    pagesize = forms.ChoiceField(widget=forms.Select(), choices=(('10', '10'),('25', '25'),('50', '50'), (u'Все', u'Все')),
                                 initial="10", required=False)

    def clean(self):
        cleaned_data = self.cleaned_data
        s = cleaned_data.get("start")
        e = cleaned_data.get("end")

        if s and e and s > e:
            raise forms.ValidationError(u"Начальная дата не должна быть позже  конечной.")
        # Always return the full collection of cleaned data.
        return cleaned_data

class FeedbackForm(forms.Form):
    email = forms.EmailField(required=True, label=u'Электропочта',
                             error_messages={"required": u"Введите адрес", "invalid": u"Неправильный формат адреса"},
                             max_length=150,widget=forms.TextInput())
    message = forms.CharField(required=True, label=u'Сообщение',
                              error_messages={"required": u"Введите сообщение"},
                              widget=forms.Textarea(attrs={'rows': 10, 'cols': 65}))
#    captcha = CaptchaField(required=True, label=u'Решите пример',
#                           error_messages={"required": u"Решите пример правильно", "invalid": u"Неправильный ответ"})

TestTaskGAE/Test/views.py
# Create your views here.
# coding=UTF-8
from cStringIO import StringIO
from datetime import datetime
#import logging
from itertools import chain
import random
import time
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect
from django.template.context import RequestContext
#from reportlab.pdfbase.pdfmetrics import registerFont
#from reportlab.pdfbase.ttfonts import TTFont
#from reportlab.pdfgen import canvas
from TestTaskGAE.Test.forms import SearchTest, FeedbackForm
from google.appengine.api import users

from TestTaskGAE.Test.models import Chapter, Task, Option, TestSession, TestSequence, Feedback
import TestTaskGAE.settings
#l = logging.getLogger('django.db.backends')
#l.setLevel(logging.DEBUG)
#l.addHandler(logging.StreamHandler())
class Summary:
    def __init__(self, taskText, correctText, actualText, link = None):
        self.task = taskText
        self.correct = correctText
        self.actual = actualText
        self.link = link

def get_params(request, additional= None):
    params = {}
    if users.get_current_user():
        params = {'teacher': (bool(request.user.groups.filter(name='teacher'))),
                  'chapter_list': Chapter.objects.filter(active=True)}
    if additional:
        params.update(additional)
    return params
def chapter_id_for_test_session(test_session):
    try:
        return test_session.answer_set.all()[0].selected.all()[0].task.chapter_id
    except Exception:
        return -1

#@login_required
def chapters(request, chapterId=None, final = None):
    if chapterId and not (final is None):
        try:
            del request.session['test']
        except KeyError:
            pass
        if final:
            request.session['final'] = final
            try:
                return test_detail(request, (
                TestSession.objects.get(student=request.user, final=True,
                                        answer__selected__task__chapter=chapterId)).id)
            except TestSession.DoesNotExist:
                pass
        testSession = TestSession()
        testSession.testDate = datetime.now()
        testSession.duration = 0
        testSession.student = request.user
        testSession.final = request.session.get('final', False)
        testSession.save()
        request.session['test'] = testSession
        #generate random list of tasks
        chapter = Chapter.objects.get(id = chapterId)
        easy = Task.objects.filter(chapter = chapterId, complexity = 1).order_by('?')[:chapter.easy]
        medium = Task.objects.filter(chapter = chapterId, complexity = 2).order_by('?')[:chapter.medium]
        hard = Task.objects.filter(chapter = chapterId, complexity = 3).order_by('?')[:chapter.hard]
        tasks = list(chain(easy, medium, hard))
        random.shuffle(tasks)
        k = 0
        for t in tasks:
            elem = TestSequence()
            elem.position = k
            elem.task = t
            elem.test_session = testSession
            elem.save()
            k += 1
        return task(request, 1)
    else:
        params = get_params(request)
        if chapterId:
            params['chapterId'] = chapterId
        return render_to_response("chapter.html", params, context_instance=RequestContext(request))
@login_required
def task(request, task_num):
    task_num  = int(task_num)
    isTeacher =  bool(request.user.groups.filter(name='teacher'))
    if isTeacher:
        return redirect("/chapter/")
    testSession = request.session.get('test')
    testSession.duration = (datetime.now() - testSession.testDate).seconds
    testSession.save()
    test_sequence = TestSequence.objects.filter(test_session = testSession).order_by('position')
    task_list = []
    type = 0
    for ts in test_sequence:
        task_list.append(ts.task)
    task = test_sequence[task_num - 1].task
    options = task.option_set.all()
    for opt in options:
        if opt.correct:
            type += 1
        if opt.value:
            type = -1

    return render_to_response("task.html", {'task': task,
                                            'type': type,
                                            'list' : task_list,
                                            'next' : task_num + 1,
                                            'tictac' : testSession.duration,
                                            'limit' : task.chapter.timeLimit,
                                            'chapter_list' : Chapter.objects.filter(active = True)},
                              context_instance=RequestContext(request))
@login_required
def add_answer(request, task_num):
    task_num = int(task_num)
    try:
        if request.method == 'POST':
            try:
                testSession = request.session['test']
            except KeyError :
                testSession = None
            tsStep = TestSequence.objects.filter(test_session = testSession, position = task_num - 2)[0]#current task

            chosen = request.POST.getlist('option')
            answers = testSession.answer_set.all()
            answer  = None
            for ans in answers:
                if ans.selected.all()[0].task == tsStep.task:
                    answer = ans
                    break
            if answer is None:
                answer = testSession.answer_set.create()
            else:
                answer.selected.clear()
            for optId in chosen:
                try:
                    opt = Option.objects.get(id = int(optId))
                    if opt.task != tsStep.task or (opt.task == tsStep.task and opt.value != '' and opt.value is not None):#a chance that entered value is ID of another option
                        raise ValueError
                    if opt.value is not None:
                        answer.selected.add(opt)#value from form is not ID but entered data
                except (Option.DoesNotExist, ValueError):
                    answer.value = optId
                    answer.selected.add(tsStep.task.option_set.all()[0])
            answer.position = task_num
            answer.save()
            if TestSequence.objects.filter(test_session = testSession).count() < task_num:
                task_num = 0
            return redirect('/chapter/{0:d}/task/{1:d}/'.format(tsStep.task.chapter_id, task_num), context_instance=RequestContext(request))
        else:
            return redirect("/chapter/")
    except Task.DoesNotExist:
        return redirect("/chapter/")

def get_test_session_data(testSession):
    answers = testSession.answer_set.all()
    aggregate = []
    testSession.correct = 0
    for a in answers:
        opts = a.selected.all()
        correctTexts = []
        actualTexts = []
        if len(opts) > 0:

            task = opts[0].task
            taskOpts = task.option_set.filter(correct=True)
            for opt in taskOpts:
                if opt.value is None or opt.value == '':
                    correctTexts.append(opt.text)
                else:
                    correctTexts.append(opt.value)
            if a.value is not None and opts[0].value != a.value:
                actualTexts.append(a.value)
            elif opts.count() == 1 and not opts[0].correct:
                actualTexts.append(opts[0].text)
            elif len(correctTexts) > 1 and set(opts).intersection(taskOpts) != set(taskOpts):
                for o in opts:
                    actualTexts.append(o.text)
            else:
                testSession.correct += 1
        aggregate.append(Summary(taskText=task.description,
                                 correctText=correctTexts, actualText=actualTexts, link = task.theoryLink))
    testSession.total = len(aggregate)
    testSession.save()
    return aggregate

@login_required
def end(request, chapter_id):
    chapter = Chapter.objects.get(id = chapter_id)
    try:
        testSession = request.session['test']
        testSession.duration = (datetime.now() - testSession.testDate).seconds
        aggregate = get_test_session_data(testSession)
        if settings.SEND_EMAIL:
            send_mail(u"Тестирование завершено", testSession.student.username + u' завершил тестирование по теме ' + chapter.shortName,
                      'frostbeast@mail.ru', [User.objects.get(username='teacher').email])
        del request.session['test']
        params = get_params(request, {'chapter' : chapter, 'session' : testSession,
                                      'time' :  time.strftime('%H:%M:%S', time.gmtime(testSession.duration)),
                                      'answers' : aggregate})
        return render_to_response("end.html", params, context_instance=RequestContext(request))
    except (KeyError, Chapter.DoesNotExist):
        return redirect("/chapter/")


@login_required
def test_detail(request, testId):
    try:
        testSession = TestSession.objects.get(id = testId)
        chapter = Chapter.objects.get(id = chapter_id_for_test_session(testSession))
        aggregate = get_test_session_data(testSession)
        params = get_params(request, {'chapter' : chapter, 'session' : testSession,
                        'time' :  time.strftime('%H:%M:%S', time.gmtime(testSession.duration)),
                        'answers' : aggregate})
        return render_to_response("end.html", params,  context_instance=RequestContext(request))
    except TestSession.DoesNotExist:
        return redirect("/chapter/")

@login_required
def students(request):
    try:
        studentGroup = Group.objects.get(name='student')
        students = studentGroup.user_set.all()
        stats = []
        start = None
        end = None
        page = None
        pagesize = 10
        if request.method == 'GET':

TestTaskGAE/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function(){

            $("ul.subnav").parent().append("<span></span>"); //Only shows drop down trigger when js is enabled - Adds empty span tag after ul.subnav

            $("ul.topnav li span").click(function() { //When trigger is clicked...

                //Following events are applied to the subnav itself (moving subnav up and down)
                $(this).parent().find("ul.subnav").slideDown('fast').show(); //Drop down the subnav on click

                $(this).parent().hover(function() {
                }, function(){
                    $(this).parent().find("ul.subnav").slideUp('slow'); //When the mouse hovers out of the subnav, move it back up
                });

                //Following events are applied to the trigger (Hover events for the trigger)
            }).hover(function() {
                        $(this).addClass("subhover"); //On hover over, add class "subhover"
                    }, function(){	//On Hover Out
                        $(this).removeClass("subhover"); //On hover out, remove class "subhover"
                    });

        });
    </script>
    <link type="text/css"  href="/static/css/base.css" rel="stylesheet"/>
    <link type="text/css" href="/static/css/cupertino/jquery-ui.css" rel="stylesheet"/>
    {% block links %}{% endblock %}
    <title>{% block title %}Тестирование{% endblock %}</title>
</head>
<body onload="{% block loader %}{% endblock %}">
<table class="back" width="760">
    <tr>
        <td valign="top" >
            {% block header %}
                <H1 id="main">{% comment %}<img src="/static/images/header_bg.jpg" alt="ГОУ 1748 ЦО Вертикаль" style="vertical-align: top;" align="left" height="90" width="250">{% endcomment %}Сайт учителя математики<br>Морозовой Ирины Сергеевны</H1>
                <table width="100%" class="gradient"><tr>
                    <td align="left" class="headerText">Пользователь: <span class="headerText highlight">
                        {% if user.is_authenticated %}{{ user.username }}
                        {% else %}Гость{% endif %}</span></td>
                    <td align="right">{% if user.is_authenticated %}<a href="/accounts/logout/">Выход</a>{% else %}<a href="/accounts/login/">Войти</a>{% endif %}</td></tr></table>
                <div class="container">
                    <ul class="topnav">
                        <li><a href="/chapter/">Главная</a></li>
                        {% if user.is_authenticated %}
                            <li>
                                <a href="#">Тестирование</a>
                                <ul class="subnav">
                                    {%  block menuinfo %}
                                        {% if teacher %}
                                            <li><a href="/statistics/students/">Статистика по студентам</a></li>
                                            <li><a href="/statistics/tests/">Статистика по тестам</a></li>
                                        {% else %}
                                            {% if chapter_list %}
                                                {% for item in chapter_list %}
                                                    <li><a href="/chapter/{{ item.id }}/"><nobr>{{item}}</nobr></a></li>
                                                {% endfor %}
                                            {% endif %}
                                        {% endif %}
                                    {% endblock %}
                                </ul>
                            </li>
                        {% endif %}
                        <li>
                            <a href="#">Информация</a>
                            <ul class="subnav">
                                <li><a href="/theory/chapter1.html">Дроби</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Обо мне</a>
                            <ul class="subnav">
                                <li><a href="/bio/">Биография</a></li>
                                <li><a href="/feedback/">Обратная связь</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            {% endblock %}

            {% block main %}{% endblock %}
        </td>
    </tr>
    {% block footer %}<tr><td valign="bottom"><span class="copyright">© 2011, Морозова Ирина, Морозов Максим, frostbite3-at-gmail.com</span></td></tr>{% endblock %}
</table>
</body>
</html>

TestTaskGAE/templates/bio.html
{% extends "base.html" %}
{% block main %}
    <H2>Лучший в мире учитель математики!</H2>
    <div>&nbsp;</div>
    <img src="http://img-fotki.yandex.ru/get/4608/karnodon.28/0_5e187_4a8600ba_L.jpg" alt="">
{% endblock %}

TestTaskGAE/templates/chapter.html
{% extends "base.html" %}
{% block title %} Разделы тестирования{% endblock %}
{% block links %}
    <style type="text/css">
        html {
            height: 650px;
        }
    </style>
{% endblock %}
{% block main %}
    <span class="mainText">
        {% if teacher or not user.is_authenticated %}
            Математика - РУЛИТ!!!
            <img src="/static/images/main_bg.jpg" alt="">
        {% else %}
            {% if chapterId %}
                <ul>
                    <li><a href="train/">Тренировочный тест</a></li>
                    <li><a href="final/">Зачетный тест</a></li>
                </ul>
            {% else %}
                Выберите раздел для тестирования
            {% endif %}
        {% endif %}
    </span>
{% endblock %}

TestTaskGAE/templates/charts.html
<html>
<head>
    <link type="text/css"  href="/static/css/base.css" rel="stylesheet"/>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/static/scripts/excanvas.min.js"></script><![endif]-->
    <script language="javascript" type="text/javascript" src="/static/scripts/jquery.flot.js"></script>
</head>
<body style="height: 30px">
<h2>Учащийся: {{ student.first_name }}&nbsp;{{ student.last_name }}, Раздел: {{ chapter.shortName }}</h2>
<div>&nbsp;</div>
{#    <img src="/statistics/chart/chapter/{{ 1 }}/student/{{ student.id }}/draw/"/>#}
<div id="placeholder" style="width:720px;height:300px;margin-left: 16px;"></div>
<script type="text/javascript">
    $(function () {
        var data = [{% for bar in stats %}['{{ forloop.counter0 }}', {{ bar.1 }}]{% if not forloop.last %},{% endif %}{% endfor %}];
        $.plot($("#placeholder"), [
            { data: data, lines: { show: true }, points:{ show: true }}
        ], {
            xaxis: {
                ticks: [{% for bar in stats %}[{{ forloop.counter0 }},{% if forloop.counter0|divisibleby:sparserate %}"{{ bar.0|date:"j.m.Y" }}"{% else %}""{% endif %}]{% if not forloop.last %},{% endif %}{% endfor %}]
            },
            yaxis: {
                ticks: {{ max }},
                min: 0,
                max: {{ max }}
            },
            grid: {
                backgroundColor: { colors: ["#fff", "#eee"] }
            }
        });
    });
</script>
</body>
</html>

TestTaskGAE/templates/end.html
{% extends "base.html" %}
{% block title %}{% if teacher %}Результаты{% else %}Конец{% endif %} {% endblock %}
{% block menu %}
    {% if teacher %}
        » <a href="/statistics/students/">Статистика по студентам</a> » Результат
    {% endif %}
{% endblock %}
{% block main %}
    {% if teacher %}
        <p>Результаты тестирования {{ session.student.first_name }} {{ session.student.last_name }} по разделу "{{ chapter }}"</p>
    {% else %}
        <p>Тестирование по разделу {{ chapter }} завершено!</p>
    {% endif %}
    <p>
        {% if teacher %}
            {{ session.student.first_name }} {{ session.student.last_name }} ответил(а)
        {% else %}
            Вы ответили
        {% endif %} правильно на {{ session.correct }} из {{ session.total }} вопросов за {{ time }}
    </p>
    {% if answers %}
        <table width="100%">
            {% for answer in answers %}
                <tr>
                    <td>
                        <div class="task first">
                            {% if answer.actual|length == 0 %}
                                <img align="middle" height="32" width="32" src="/static/images/checkmark.png">
                            {% else %}
                                <img align="middle" height="32" width="32" src="/static/images/error.png">
                            {% endif %} {{ answer.task|safe }} {% if answer.actual|length > 0  and answer.link %} <a href="{{ answer.link }}">Теория</a>{% endif %}
                        </div>
                        {% if session.final or teacher or answer.actual|length == 0%}
                            <div class="task correct {% if answer.actual|length == 0 %}last{% endif %}">
                                Правильно
                                <ul>
                                    {% for item in answer.correct %}
                                        <li>{{ item|safe }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        {% if answer.actual|length > 0 %}
                            <div class="incorrect task last">
                                Неправильно
                                <ul >
                                    {% for item in answer.actual %}
                                        <li>{{ item|safe }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

TestTaskGAE/templates/feedback.html
{% extends "base.html" %}
{% block main %}
    <h2>Обратная связь</h2>
    <div id="feedbackform">
        {% if human %}
            Спасибо за ваше сообщение. Ваше мнение очень важно для нас.<br>
        {% endif %}
        Введите текст сообщения и нажмите кнопку "Отправить"
        <form method="POST">
            {% if form.non_field_errors %}
                <div>
                    {% for err in form.non_field_errors %}
                        <div class="errormessage">{{ err }}</div>
                    {% endfor %}
                </div>
            {% endif %}
            {% for field in form.visible_fields %}
                {% for err in field.errors %}
                    <div class="errormessage">{{ err }}</div>
                {% endfor %}
            {% endfor %}
            <ul>
                {% for field in form.visible_fields %}
                    {% if field.name != form.pagesize.name %}
                        <li {% if field.errors %}class="field_error"{% endif %}>
                            <div style="width: 150px;">{{ field.label_tag }}</div>
                            {{ field }}
                        </li>
                    {% endif %}
                {% endfor %}
                <li>
                    <input type="submit" title="Отправить" value="Отправить" id="feedback_button">
                </li>
            </ul>
        </form>
    </div>
    <script type="text/javascript">
        $(function() {
            $( "input:submit" ).button();
        });
    </script>
{% endblock %}

TestTaskGAE/templates/searchform.html
<div id="searchform">
    <form method="GET">
        {% if form.non_field_errors %}
            <div>
                {% for err in form.non_field_errors %}
                    <div class="errormessage">{{ err }}</div>
                {% endfor %}
            </div>
        {% endif %}
        {% for field in form.visible_fields %}
            {% for err in field.errors %}
                <div class="errormessage">{{ err }}</div>
            {% endfor %}
        {% endfor %}
        <ul>
            {% for field in form.visible_fields %}
                {% if field.name != form.pagesize.name %}
                    <li {% if field.errors %}class="field_error"{% endif %}>
                        {{ field.label_tag }}
                        {{ field }}
                    </li>
                {% endif %}
            {% endfor %}
            <li>
                <input type="submit" title="Найти" value="Найти">
            </li>
        </ul>

        {{ form.page }}
        <div class="pagination">
            {% if stats.paginator and stats.paginator.num_pages > 1%}
                <span class="step-links">
                    {% if stats.has_previous %}
                        <a id="prev" href="#"><<</a>
                    {% endif %}
                    <span class="current">
                        {% for pn in stats.paginator.page_range %}
                            <a href="#" class="{% if pn == stats.number%}active{% endif %} pagelink">&nbsp;{{ pn }}&nbsp;</a>
                        {% endfor %}
                    </span>
                    {% if stats.has_next %}
                        <a id="next" href="#">>></a>
                    {% endif %}
                </span>
            {% endif %}
            {{ form.pagesize }}
        </div>
    </form>
</div>
<script>
    $(function() {
        $.datepicker.setDefaults( $.datepicker.regional[ "ru" ]);
        $( "#id_start" ).datepicker( );
        $( "#id_end" ).datepicker( );
        $( "input:submit" ).button();
    });
    $('#next').click(
            function() {
                var val = $('#id_page').val();
                if (val == "")
                    val = 1;
                $('#id_page').val(parseInt(val) + 1);
                $('#searchform form').submit();
            }
    );
    $('#prev').click(
            function() {
                $('#id_page').val(parseInt($('#id_page').val()) - 1);
                $('#searchform form').submit();
            }
    );
    $('.pagelink').click(
            function() {
                $('#id_page').val(parseInt($(this).text()));
                $('#searchform form').submit();
            }
    )
</script>